name: test-workflow

on: 
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print a welcome messafe
        run: echo "Welcome to github actions"

  
