name: test-workflow

on: 
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print a welcome messafe
        run: echo "Welcome to github actions"
      - name: Checkout repository
        uses: actions/checkout@v7.0.1

      - name: list repository files
        run: ls -la
