on:
  push:
    branches:
      - main
      - "release/**"
    paths:
      - "src/**"
  pull_request:
    branches:
      - main
      - "release/**"


jobs:
  test:
    runs-on: ubunto-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Run test
        run: npm test



